### PR TITLE
update granite documentation

### PR DESCRIPTION
**Pull request by drujensen**
This removes the duplicate granite documentation

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
@drujensen Is there no way to just reuse the current Granite docs?  Having to maintain two separate documentation bases makes it really easy or stuff to get out of sync.

**Comment by drujensen** [comment]
@Blacksmoke16 We could change the link in Granite to point here or we can change the link here to point to Granite.  Which one do you think is more complete/correct?

**Comment by Blacksmoke16** [comment]
@drujensen It would be easiest to change the link to point to Granite.  It's more likely to get updated as things change.

**Comment by drujensen** [comment]
much easier than I thought it would be

**Pull request merged**
